title: GUIDJIME ADINSI Ahouahounko TÃ©lesphore
theme: jekyll-theme-minimal
#logo: head_shot_circle.png
logo: head_square.jpg
show_downloads: False
#description: Data Scientist and AI/ML Engineer with expertise in Machine Learning, Deep Learning, and Generative AI.
